allprojects {
    repositories {
        mavenLocal()
        maven { url = uri("/opt/local-maven-repo") }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    buildscript {
        repositories {
            mavenLocal()
            maven { url = uri("/opt/local-maven-repo") }
            google()
            mavenCentral()
            gradlePluginPortal()
        }
    }
}

settingsEvaluated { settings ->
    settings.pluginManagement {
        repositories {
            mavenLocal()
            maven { url = uri("/opt/local-maven-repo") }
            google()
            mavenCentral()
            gradlePluginPortal()
        }
    }
    settings.dependencyResolutionManagement {
        repositories {
            mavenLocal()
            maven { url = uri("/opt/local-maven-repo") }
            google()
            mavenCentral()
        }
    }
}